In [1]:
import numpy as np

# Aca implementare la forward 

In [2]:
def forward(a,b):
    '''Funcion que retorna un array "x" despues de hacer la sustitucion forward'''
    n = a.shape[0] # la dimension de la matriz 
    
    # https://numpy.org/doc/1.18/reference/generated/numpy.ndarray.html
    # estamos creando un matriz columna 
    x = np.ndarray( shape=(n,1), dtype = np.float64 )
    
    ### TODO DENTRO DE UN FOR . (ELIMINA)#### 
    # espero se entienda el por que del -1 
    x[n-1] = b[n-1]/a[n-1][n-1] # comenzamos por el ultimo
       
    # luego hacemos el algoritmos de adelante hacia atras
    # "i" en general siempre se referira a filas y "j" a columnas
    
    # Espero se entienda el por que de "n-2"
    # es debido a la funcion range(start,final,pasos)
    for i in range(n-2,-1,-1):
        
        # sera que hara cuenta de todo lo que se restara a b[i]
        # lo ponemos aqui debido a no llamarla demasiadas veces
        summ = b[i] 
    
        for j in range(i+1,n):
            summ -= a[i][j]*x[j]
        
        # finalmente asignamos
        x[i] = summ/a[i][i]
    

    
    return x

In [3]:
print(" ######## PREGUNTA NUMERO 1A ############## ")
# con el dtype me aseguro que todos seran floats de 64 bits        
M = np.array( [[1,2,1],[0,-4,1],[0,0,-2]] , dtype= np.float64 )
N = np.array( [[5],[2],[4]] , dtype= np.float64 )

print("Sistema de ecuaciones a resolver del problema 1(a)\n")
for i in range(0,len(N)):
    print(f'{M[i,0]}*x1 + {M[i,1]}*x2 + {M[i,2]}*x3 = {N[i,0]}')

X = forward(M,N)
print("Respuesta es : \n")
for i in range(0,len(X)):
    print(f'x{i+1} es : {X[i]}')


 ######## PREGUNTA NUMERO 1A ############## 
Sistema de ecuaciones a resolver del problema 1(a)

1.0*x1 + 2.0*x2 + 1.0*x3 = 5.0
0.0*x1 + -4.0*x2 + 1.0*x3 = 2.0
0.0*x1 + 0.0*x2 + -2.0*x3 = 4.0
Respuesta es : 

x1 es : [9.]
x2 es : [-1.]
x3 es : [-2.]


# Aca implementare backward 

In [4]:
# # Aca implementare backward 

def backward(a,b):
    '''Funcion que retorna un array "x" despues de hacer la sustitucion backward '''
    
    n = a.shape[0] # la dimension de la matriz 
    # https://numpy.org/doc/1.18/reference/generated/numpy.ndarray.html
    # estamos creando un matriz columna 
    x = np.ndarray( shape=(n,1), dtype = np.float64 )
    x[0] = b[0]/a[0][0] # comenzamos con el primero
       

    for i in range(1,n):
        # lo ponemos aqui debido a no llamarla demasiadas veces
        summ = b[i] 
        for j in range(0,i):
            summ -= a[i][j]*x[j]
        # finalmente asignamos
        x[i] = summ/a[i][i]
    
    return x

In [5]:
print(" ######## PREGUNTA NUMERO 1B ############## ")
# con el dtype me aseguro que todos seran floats de 64 bits        
M = np.array( [[2,0,0],[1,4,0],[4,3,3]] , dtype= np.float64 )
N = np.array( [[4],[2],[5]] , dtype= np.float64 )

print("Sistema de ecuaciones a resolver del problema 1(b)\n")
for i in range(0,len(N)):
    print(f'{M[i,0]}*x1 + {M[i,1]}*x2 + {M[i,2]}*x3 = {N[i,0]}')

X = backward(M,N)
print("Respuesta es : \n")
for i in range(0,len(X)):
    print(f'x{i+1} es : {X[i]}')


 ######## PREGUNTA NUMERO 1B ############## 
Sistema de ecuaciones a resolver del problema 1(b)

2.0*x1 + 0.0*x2 + 0.0*x3 = 4.0
1.0*x1 + 4.0*x2 + 0.0*x3 = 2.0
4.0*x1 + 3.0*x2 + 3.0*x3 = 5.0
Respuesta es : 

x1 es : [2.]
x2 es : [0.]
x3 es : [-1.]


# Aca implementare el Naive Gauss 

In [6]:
def naive_gauss(a,b):
    '''Funcion que retorna un array "x" despues de hacer una eliminacion de Gauss sin pivoteo'''
    
    n = a.shape[0] # la dimension de mi matriz 
    # https://numpy.org/doc/1.18/reference/generated/numpy.ndarray.html
    # estamos creando un matriz columna 
    x = np.ndarray( shape=(n,1), dtype = np.float64 )
    
    
    
    # el -1 es para indicar que recorreremos n-1 filas 
    # ya que al final la ultima fila no sera necesario 
    # hacer un eliminacion 
    for k in range(0,n-1):
        
        # ###### ELIMINACION DE GAUSS (FORWARD) ############
        # este indice recorrera las filas 
        # haciendo ceros 
        for i in range(k+1,n):
            
            # esta variable se crea con el fin de no calcularla 
            # muchas veces dentro del bucle del "j"
            xmult = a[i][k]/a[k][k] 
            # en principio a[i][k] es 0 como esperamos pero 
            # esto no sirve para nuestros fines . Para usar mejor el
            # algoritmo guardamos los multiplicadores que para el metodo
            # de LU nos vendra bien 
            a[i][k] = xmult  
            
            # este indice hara el seguimiento de los 
            # los cambios a los demas elementos de la fila
            for j in range(k+1,len(a)):
                # hacemos los cambios en fila completa
                a[i][j] -= xmult*a[k][j]
            
            # hacemos por separado el cambio al elemento de "b"
            b[i] -= xmult*b[k]
    
    # ###### SUBSTITUCION INVERSA(BACKWARD) ######## 
    # espero se entienda el por que del -1 
    x[n-1] = b[n-1]/a[n-1][n-1] # comenzamos por el ultimo
       
    # luego hacemos el algoritmos de adelante hacia atras
    # "i" en general siempre se referira a filas y "j" a columnas
    
    # Espero se entienda el por que de "n-2"
    # es debido a la funcion range(start,final,pasos)
    for i in range(n-2,-1,-1):
        
        # sera que hara cuenta de todo lo que se restara a b[i]
        # lo ponemos aqui debido a no llamarla demasiadas veces
        summ = b[i] 
        
        for j in range(i+1,n):
            summ -= a[i][j]*x[j]
        
        # finalmente asignamos
        x[i] = summ/a[i][i]
    
    return x

In [7]:
print(" ######## EJEMPLO PARA PROBAR GAUSS SIN PIVOTEO ############## ")
# con el dtype me aseguro que todos seran floats de 64 bits        
M = np.array( [[3,2,4],[5,3,10],[9,10,12]] , dtype= np.float64 )
N = np.array( [[1],[4],[5]] , dtype= np.float64 )

print("Sistema de ecuaciones a resolver usando Gauss sin pivoteo(ejemplo)\n")
for i in range(0,len(N)):
    print(f'{M[i,0]}*x1 + {M[i,1]}*x2 + {M[i,2]}*x3 = {N[i,0]}')

X = naive_gauss(M,N)
print("Respuesta es : \n")
for i in range(0,len(X)):
    print(f'x{i+1} es : {X[i]}')

 ######## EJEMPLO PARA PROBAR GAUSS SIN PIVOTEO ############## 
Sistema de ecuaciones a resolver usando Gauss sin pivoteo(ejemplo)

3.0*x1 + 2.0*x2 + 4.0*x3 = 1.0
5.0*x1 + 3.0*x2 + 10.0*x3 = 4.0
9.0*x1 + 10.0*x2 + 12.0*x3 = 5.0
Respuesta es : 

x1 es : [-1.]
x2 es : [0.5]
x3 es : [0.75]


# El procedimeinto que lleva a cabo del metodo de eliminacion de Gauss con pivoteo parcial lo llamaremos "gauss"

In [8]:
# Funcion de la que me tomo mas tiempo hacerlo 
def gauss(a,b):
    '''Funcion que retorna un array "x" despues de hacer una eliminacion de Gauss con pivoteo'''
    
    n = a.shape[0]
    # https://numpy.org/doc/1.18/reference/generated/numpy.ndarray.html
    # estamos creando un matriz columna 
    x = np.ndarray( shape=(n,1), dtype = np.float64 )   
    a_copy = a.copy() # con el fin de hacer segumiento a la matriz al final . 
    s = [] # lista para alojar los valores maximos (es parte del pivoteo)
    l = [] # usada para reordenar como se hara la eliminacion
    
    # #### LLENAMOS LA LISTA "S" CON LOS VALORES MAXIMOS  #######
    for i in range(0,n):
        l.append(i) # vamos agregando .Establecemos esta matriz
        smax = 0 # el maximo de una fila es importante para el pivote
        for j in range(0,n):
            # se escoje el maximo entre todos los elemnos de una fila
            smax = max(smax,abs(a[i][j])) 
            
        s.append(smax) # alojamos el maximo de la fila
    
    # ---------- print('l inicial ' ,l) (SEGUIMIENTO)
    # --------- print('s inicial ', s) (SEGUIMIENTO)
    
    # ##### PIVOTEO(ESCOJEMOS LA FILAS PIVOTES Y ELIMINAMOS) #########
    # k hace referencia a la columna donde se hara ceros seran creados en el array a_ij
    # Pero recuerda que los ceros no se crean realmente . Por que en esos espacios almacenamos 
    # otras cosas(los multiplicadorese para descomposicion LU) . 
    for k in range(0,n-1):
        
        rmax = 0 
        # ##### SE ESCOJE LA FILA PIVOTE EN ESTE BLOQUE #########
        for i in range (k,n):
            
            # esto es para escoger la correcta fila pivote
            # se esta dividiendo (elemnto de columna k y fila [k-n][k])/los Smax
            r = abs( a[l[i]][k] / s[l[i]] )
            if (r > rmax):
                # j = i es para escoger el correcto pivote
                # rmax = r es para escoger la maxima proporcion(ratio)
                rmax,j = r,i
                # al final no usaremos rmax , solo es necesario para detener el if cuando sea necesario
              
        l[j],l[k] = l[k],l[j] # luego se cambia el lugar donde ocurre el maximo proporcion
        
        
        # ####### ELIMINACION GAUSSIANA PERO LA FILA PIVOTE LO DETERMINA "l" ################## 
        for i in range(k+1,n):
            xmult = a[l[i]][k]/a[l[k]][k]
            a[l[i]][k] = xmult # los guardo para fines de LU y para eliminar "b"
            
            a_copy[l[i]][k] -= xmult*a[l[k]][k] # para hacer segumiento(se puede borrar) 
            
            # este for hara segumiento de que se haga operaciones en toda la fila que no es pivot
            for j in range(k+1,n):
                a[l[i]][j] -= xmult*a[l[k]][j]
                a_copy[l[i]][j] -= xmult*a[l[k]][j] # para hacer seguimiento(se puede borrar)
    
    # --------- print('l final ' ,l) (SEGUIMIENTO)
    # --------- print('a final copy \n' , a_copy) (SEGUIMIENTO)
    # ##### SEGIMOS PIVOTEANDO PERO PARA LA MATRIZ b###   
    for k in range(0,n-1):
        
        # recuerda el que ahora maneja el orden sera la lista "l"
        # debemos hacer las operaciones en el mismo orden que hemos hecho para "a"
        for i in range(k+1,n):
            b[l[i]] -= a[l[i]][k]*b[l[k]]
            
    #------ print('b final \n ' , b) (SEGUIMIENTO)
    
    # ######### AHORA HACEMOS LA SUSTITUCION BACKWARD ##########
    
    # espero se entienda por que -1 . Es por la cuenta por cero
    x[n-1] = b[l[n-1]]/a[l[n-1]][n-1]
    
    for i in range(n-2,-1,-1):
        summ = b[l[i]]
        for j in range(i+1,n):
            summ -= a[l[i]][j]*x[j]
            
        x[i] = summ/a[l[i]][i]
        
        
    return x
        

In [9]:
print(" ######## EJEMPLO PARA PROBAR GAUSS CON PIVOTEO ############## ")
# con el dtype me aseguro que todos seran floats de 64 bits        
M = np.array( [[3,-13,9,3],[-6,4,1,-18],[6,-2,2,4],
              [12,-8,6,10]] , dtype= np.float64 )
N = np.array( [[-19],[-34],[16],[26]] , dtype= np.float64 )

print("Sistema de ecuaciones a resolver usando Gauss con pivoteo(ejemplo)\n")
for i in range(0,len(N)):
    print(f'{M[i,0]}*x1 + {M[i,1]}*x2 + {M[i,2]}*x3 +{M[i,3]}*x4= {N[i,0]}')

X = gauss(M,N)
print("Respuesta es : \n")
for i in range(0,len(X)):
    print(f'x{i+1} es : {X[i]}')

 ######## EJEMPLO PARA PROBAR GAUSS CON PIVOTEO ############## 
Sistema de ecuaciones a resolver usando Gauss con pivoteo(ejemplo)

3.0*x1 + -13.0*x2 + 9.0*x3 +3.0*x4= -19.0
-6.0*x1 + 4.0*x2 + 1.0*x3 +-18.0*x4= -34.0
6.0*x1 + -2.0*x2 + 2.0*x3 +4.0*x4= 16.0
12.0*x1 + -8.0*x2 + 6.0*x3 +10.0*x4= 26.0
Respuesta es : 

x1 es : [3.]
x2 es : [1.]
x3 es : [-2.]
x4 es : [1.]


# Aca implementare la descomposicion LU a una MATRIZ invertible . 

In [10]:
# nos basamos en el algoritmo de CROUT
def descom_LU(a):
    'Algortimo que recibe una matriz invertible y le hace la descomposicion LU'
    
    n = a.shape[0]
    # creamos los espacios . Estos si seran fijos
    # para ver como funcion np.zeros
    # https://numpy.org/doc/stable/reference/generated/numpy.zeros.html
    l = np.zeros(shape=(n,n), dtype=np.float64)
    u = np.zeros(shape=(n,n), dtype=np.float64)
    
    for k in range(0,n):
        l[k][k] = 1
        ###### USA OTRO INDICE PARA TENER SOLO UN FOR #####
        for j in range(k,n):
            
            ####### hacemos u_ij = a_kj - SumEn"s"_{0}^{k-1}l_ks*u_sj #########
            
            # seleccionamos una fila k de la matriz "l"
            l_fila = np.array(l[k])
            # seleccionamos la columna j de la matriz "u"
            u_colum = np.array([c[j] for c in u])
            
            
            # Para ver como funciona la funcion suma 
            # https://numpy.org/doc/stable/reference/generated/numpy.sum.html
            # se multiplican elemento por elemento . Es el poder de numpy . 
            u[k][j] = a[k][j]-np.sum(l_fila[:k]*u_colum[:k]) 
            # OJO ( es k y no k-1 ) . Eso es por la cuenta desde cero
            # Una lista vacia . Su suma es cero 
        
        for i in range(k+1,n):
            
            # seleccionamos una fila "i" de la matriz "l"
            l_fila = np.array(l[i])
            # seleccionamos la columna k de la matriz "u"
            u_colum = np.array([c[k] for c in u])
                        
            l[i][k] = (a[i][k]- np.sum(l_fila[:k]*u_colum[:k]) ) / u[k][k]
    
    return l,u
        

#  Aca implementare la resolucion de sistemas de ecuaciones lineales por Metodo de LU 

In [20]:
def solucion_por_LU(a,b):
    '''Fucion que devuelve un array x despues de resolver el sistema de
    ecuaciones por el metodo de descomposicion LU'''
    L,U = descom_LU(a) # descompone la matriz
    print('Matriz A\n', a)
    print('Matriz L\n', L)
    print('Matriz U\n', U)
    print('evaluacion \n', L.dot(U) )
    
    z = backward(L,b) # resulve el primer sitema de ecuacion
    x = forward(U,z) # resuelve el segundo sistema
    
    return x 

In [21]:
print(" ######## PREGUNTA NUMERO 3 RESUELTO CON DESCOMPOSICION LU ############## ")
# con el dtype me aseguro que todos seran floats de 64 bits   
g = 9.8
M = np.array( [[30,-20,0],[-20,30,-10],[0,-10,+10]] , dtype= np.float64 )
N = np.array( [[g],[g],[g]] , dtype= np.float64 )

print("Sistema de ecuaciones de la (pregunta 3) usando descomposicion de LU\n")
for i in range(0,len(N)):
    print(f'{M[i,0]}*x1 + {M[i,1]}*x2 + {M[i,2]}*x3 = {N[i,0]}')

X = solucion_por_LU(M,N)
print("Respuesta es : \n")
for i in range(0,len(X)):
    print(f'x{i+1} es : {X[i]}')

 ######## PREGUNTA NUMERO 3 RESUELTO CON DESCOMPOSICION LU ############## 
Sistema de ecuaciones de la (pregunta 3) usando descomposicion de LU

30.0*x1 + -20.0*x2 + 0.0*x3 = 9.8
-20.0*x1 + 30.0*x2 + -10.0*x3 = 9.8
0.0*x1 + -10.0*x2 + 10.0*x3 = 9.8
Matriz A
 [[ 30. -20.   0.]
 [-20.  30. -10.]
 [  0. -10.  10.]]
Matriz L
 [[ 1.          0.          0.        ]
 [-0.66666667  1.          0.        ]
 [ 0.         -0.6         1.        ]]
Matriz U
 [[ 30.         -20.           0.        ]
 [  0.          16.66666667 -10.        ]
 [  0.           0.           4.        ]]
evaluacion 
 [[ 30. -20.   0.]
 [-20.  30. -10.]
 [  0. -10.  10.]]
Respuesta es : 

x1 es : [2.94]
x2 es : [3.92]
x3 es : [4.9]


# Aca hare la descomposicion de cholesky . 

In [13]:
def descom_cholesky(a):
    
    n = a.shape[0]
    # creamos la matriz fija L
    l = np.zeros(shape=(n,n), dtype=np.float64)
    
    for k in range(0,n):
        
        # hagamos (l_kk = a_kk - SumEn"s"_{0}^{k-1}l_ks^2)
        
        sum1 = 0 # esta suma sera para restar a a_kk
        for s in range(0,k):
            sum1 += l[k][s]**2
        
        l[k][k] = (a[k][k]-sum1)**0.5
        
        for i in range(k+1,n):
            sum2 = 0 # sera una suma diferente 
            for s in range(0,k):
                sum2 += l[i][s]*l[k][s]
            
            l[i][k] = (a[i][k]-sum2)/l[k][k]
        
    return l
    

# # Aca implementare la resolucion de sistemas de ecuaciones lineales por Metodo de cholesky 

In [43]:
def solucion_por_cholesky(a,b):
    '''Fucion que devuelve un array x despues de resolver el sistema de
    ecuaciones por el metodo de cholesky'''
    L = descom_cholesky(a) # descompone la matriz
    print('Matriz A\n', a)
    print('Matriz L\n', L)
    
    z = backward(L,b) # resulve el primer sitema de ecuacion
    x = forward(L.T,z) # resuelve el segundo sistema
    
    return x 

In [51]:
print(" ######## PREGUNTA NUMERO 3 RESUELTO POR DESCOMPOSICION DE CHOLESKY ############## ")
# con el dtype me aseguro que todos seran floats de 64 bits   
g = 9.8
M = np.array( [[30,-20,0],[-20,30,-10],[0,-10,+10]] , dtype= np.float64 )
N = np.array( [[g],[g],[g]] , dtype= np.float64 )

print("Sistema de ecuaciones de la (pregunta 3) usando descomposicion de cholesky\n")
for i in range(0,len(N)):
    print(f'{M[i,0]}*x1 + {M[i,1]}*x2 + {M[i,2]}*x3 = {N[i,0]}')

X = solucion_por_cholesky(M,N)
print("Respuesta es : \n")
for i in range(0,len(X)):
    print(f'x{i+1} es : {X[i]}')


 ######## PREGUNTA NUMERO 3 RESUELTO POR DESCOMPOSICION DE CHOLESKY ############## 
Sistema de ecuaciones de la (pregunta 3) usando descomposicion de cholesky

30.0*x1 + -20.0*x2 + 10.0*x3 = 9.8
-20.0*x1 + 30.0*x2 + -10.0*x3 = 9.8
0.0*x1 + -10.0*x2 + 10.0*x3 = 9.8
[[ 30. -20.  10.]
 [-20.  30. -10.]
 [  0. -10.  10.]]
Matriz A
 [[ 30. -20.  10.]
 [-20.  30. -10.]
 [  0. -10.  10.]]
Matriz L
 [[ 5.47722558  0.          0.        ]
 [-3.65148372  4.0824829   0.        ]
 [ 0.         -2.44948974  2.        ]]
[[ 30. -20.   0.]
 [-20.  30. -10.]
 [  0. -10.  10.]]
[[2.94]
 [3.92]
 [4.9 ]]
Respuesta es : 

x1 es : [2.94]
x2 es : [3.92]
x3 es : [4.9]


# Pregunta 2

In [1]:
# encontremos para una matriz cualquiera la regla de correspondencia
def matriz_resistor(n):
    '''
    funcion que crea la matriz que resuelve el problema 
    de la resistencia con N nodos y tambien la matriz b 
    '''
    A = np.zeros(shape=(n,n), dtype=np.float64)
    # llenamos las dos primeras filas y dos primeras columnas 
    # que son particulares 
    A[0][0:4] = [3,-1,-1,0]
    A[1][0:4] = [-1,4,-1,-1]
    A[n-2][n-4:n] = [-1,-1,4,-1]
    A[n-1][n-4:n] = [0,-1,-1,3]
    # ese rango es debido a que llenamos ya la fila 0,1,n,n-1
    for i in range(2,n-2):
        for j in range(0,n):
            if j == i :
                A[i,j] = 4
                A[i,j-1] = -1
                A[i,j-2] = -1
                A[i,j+1] = -1
                A[i,j+2] = -1 
                
    # Definimos tambien el vector W 
    cola_inicial = [5,5]
    cola_final = [0]*(n-2)
    
    b = np.array(cola_inicial + cola_final)
    
    
    return A ,b

In [17]:
print(" ######## PREGUNTA NUMERO 2 RESUELTO POR DIFERENTES METODOS ############## ")
A,b = matriz_resistor(100)

# recuerda que los argumentos se pasar por referencia y no por valor 
# por eso uso la funcion copy
print("resolviendo con el metodo de gauss con pivoteo")
X = gauss(A.copy(),b.copy()) 
print("Respuesta es : \n")
for i in range(0,len(X)):
    print(f'V{i+1} es : {X[i]}')

print("resolviendo con el metodo de descomposicion LU\n")
X = solucion_por_LU(A.copy(),b.copy()) 
print("Respuesta es : \n")
for i in range(0,len(X)):
    print(f'V{i+1} es : {X[i]}')
    
print("resolviendo con el metodo de descomposicion de cholesky\n")
X = solucion_por_cholesky(A.copy(),b.copy()) 
print("Respuesta es : \n")
for i in range(0,len(X)):
    print(f'V{i+1} es : {X[i]}')


 ######## PREGUNTA NUMERO 2 RESUELTO POR DIFERENTES METODOS ############## 
resolviendo con el metodo de gauss con pivoteo
Respuesta es : 

V1 es : [4.89123004]
V2 es : [4.86555293]
V3 es : [4.80813718]
V4 es : [4.76284451]
V5 es : [4.71292124]
V6 es : [4.6647667]
V7 es : [4.61593656]
V8 es : [4.56736448]
V9 es : [4.51869383]
V10 es : [4.47006083]
V11 es : [4.42141345]
V12 es : [4.37277156]
V13 es : [4.32412757]
V14 es : [4.27548439]
V15 es : [4.2268409]
V16 es : [4.17819752]
V17 es : [4.12955411]
V18 es : [4.0809107]
V19 es : [4.0322673]
V20 es : [3.98362389]
V21 es : [3.93498048]
V22 es : [3.88633708]
V23 es : [3.83769367]
V24 es : [3.78905027]
V25 es : [3.74040686]
V26 es : [3.69176345]
V27 es : [3.64312005]
V28 es : [3.59447664]
V29 es : [3.54583323]
V30 es : [3.49718983]
V31 es : [3.44854642]
V32 es : [3.39990302]
V33 es : [3.35125961]
V34 es : [3.3026162]
V35 es : [3.2539728]
V36 es : [3.20532939]
V37 es : [3.15668598]
V38 es : [3.10804258]
V39 es : [3.05939917]
V40 es : [3.01075